spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://localhost:3306/dbloja
    username: jonataslaet
    password: blendo273
  jpa:
    hibernate:
      ddl-auto: update
