server: 
  port: 8081

spring:
  application:
    name: 'fornecedor'
  datasource:
    url: jdbc:mysql://localhost:3306/dbfornecedor
    username: jonataslaet
    password: blendo273
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka