server:
  port: 8888
 
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/jonataslaet/microfloricultura
          search-paths: config/fornecedor, config/loja, config/transportador