server:
  port: 8888
 
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: /home/maida/meuworkspace/microfloricultura/config